//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodStaff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodStaff()
        {
            this.ProductFoodStuff = new HashSet<ProductFoodStuff>();
        }
    
        public int FoodStuffID { get; set; }
        public string Title { get; set; }
        public decimal CountInStock { get; set; }
        public decimal MinCount { get; set; }
        public int UnitID { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductFoodStuff> ProductFoodStuff { get; set; }
    }
}
