//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCombo
    {
        public int OrderID { get; set; }
        public int ComboID { get; set; }
        public Nullable<int> Count { get; set; }
        public int OrderComboID { get; set; }
    
        public virtual Combo Combo { get; set; }
        public virtual Order Order { get; set; }
    }
}
