//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFoodStuff
    {
        public int ProductID { get; set; }
        public int FoodStaffID { get; set; }
        public Nullable<decimal> Count { get; set; }
        public int ProductFoodStaffID { get; set; }
    
        public virtual FoodStaff FoodStaff { get; set; }
        public virtual Product Product { get; set; }
    }
}
